[Eth]
NetworkId = 16
NoPruning = false
NoPrefetch = false
LightPeers = 100
EnablePreimageRecording = false
EWASMInterpreter = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 30
NoDiscovery = true
StaticNodes = ["enode://139a7d22715e0871d8702010a33c8df01630d0428a3bc3eb360a5c48e80472a755c2f712113639494e927f7bcac924aca000830873f9f84172fbffa6d0ad5786@57.181.54.54:10555"]
ListenAddr = ":30555"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 1360
Level = "debug"
MaxBackups = 8
MaxAge =5
FileRoot = ""


